services:
  redis:
    image: redis/redis-stack-server
    ports:
      - "16379:6379"
    container_name: redis
    hostname: redis
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    container_name: redis-commander
    hostname: redis-commander
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge