server:
  port: 9191


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/second_market?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 690501LJK

#  redis:
#    port: 6379
#    host: localhost

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true